config/routes.rb
Orin::Application.routes.draw do
  Mercury::Engine.routes

  namespace :mercury do
    resources :images
  end

  mount Mercury::Engine => '/'

  devise_for :users

  root to: 'topics#index'

  resource :home, only: :index
  
  resources :replies, only: :create do
    member do
      get :all
    end
  end
  
  resources :topics do
    member do
      post :mercury_update
    end
  end
end

app/models/mercury/image.rb
class Mercury::Image < ActiveRecord::Base

  self.table_name = :mercury_images

  has_attached_file :image, :path => ":rails_root/public/system/:attachment/:id/:style/:filename",
    :url => "/system/:attachment/:id/:style/:filename"

  delegate :url, :to => :image

  def serializable_hash(options = nil)
    options ||= {}
    options[:methods] ||= []
    options[:methods] << :url
    super(options)
  end

  attr_accessible :image
  
end

app/models/reply.rb
class Reply < ActiveRecord::Base
  belongs_to :topic, :inverse_of => :replies
  belongs_to :user, :inverse_of => :replies
  attr_accessible :content, :created_at, :updated_at, :user

  validates :content, :user, :topic, :presence => true

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :user
  attr_accessible :content, :edited_at, :title

  has_many :replies, :dependent => :destroy

  validates :content, :user, :presence => true
  
  def bind_images(ids)
    ids.each do |id|
      image = Mercury::Image.find(id)
      if image
        @logger ||= Logger.new("log/debug")
        @logger << mercury_images
        @logger << "\n"
      end
    end

  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include Gravtastic
  gravtastic :secure => false, :size => 48, :rating => 'G'

  devise :database_authenticatable, :confirmable, :lockable, :recoverable,
    :rememberable, :registerable, :trackable, :timeoutable, :validatable,
    :token_authenticatable

  attr_accessible :email, :password, :password_confirmation, :username, :remember_me, :login

  has_many :topics, :dependent => :destroy
  has_many :replies, :dependent => :destroy
  
  validates :username, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  helper_method :mercury_editor_path_helper

  protected

  def mercury_editor_path_helper(path)
    "/editor" + path
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!, :only => :token

  def index
  end

  def token
  end
end

app/controllers/mercury/images_controller.rb
class Mercury::ImagesController < MercuryController

  respond_to :json

  # POST /images.json
  def create
    @image = Mercury::Image.new(params[:image])
    @image.save

    respond_with @image
  end

  # DELETE /images/1.json
  def destroy
    @image = Mercury::Image.find(params[:id])
    @image.destroy
    respond_with @image
  end
  
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController

  def all
    respond_to do |format|
      replies = Topic.find(params[:id]).replies

      data_return = Hash.new
      data_return[:topic_id] = params[:id]
      data_return[:replies] = replies

      format.json { render :json => data_return.to_json }
    end 
  end

  def create
    respond_to do |format|
      reply = Topic.find(params[:topic_id]).replies.build(
        :user => current_user,
        :created_at => Time.now.utc,
        :updated_at => Time.now.utc,
        :content => params[:content]
      )
      #logger.info "#{current_user.gravatar_url(:size => 30)}\n"
      if reply.save
        format.json { render :text => '1', :status => 201 }
      else
        format.json { render :text => '0', :status => 501 }
      end  
    end
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.order('updated_at DESC')
  end
  
  def new
    @topic = Topic.new
  end
  
  def create
    @topic = current_user.topics.build
    @topic.content = params[:content][:topic_content][:value]

    begin
      @topic.save!
    rescue
    end

    render text: '{}'
  end

  def show
  end
  
  def edit
    @topic = Topic.find(params[:id])
  end

  def mercury_update
    @topic = Topic.find(params[:id])
    @topic.content = params[:content][:topic_content][:value]
    begin
      @topic.save!
    rescue
    end
    render text: '{}'
  end

  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy

    respond_to do |format|
      format.html do
        redirect_to topics_url
      end
    end
  end

  private

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/reply_helper.rb
module ReplyHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/home/index.haml
#main
  .container
    .row
      #operation-bar.span4.offset4
        - if user_signed_in?
          %section.box
            = link_to t('.new_topic'), mercury_edit_path_helper(new_topic_path), :class => 'btn btn-large btn-primary'

app/views/layouts/_flash_content.haml
.container
  .row
    .span8.offset2
      - flash.each do |name, msg|
        -if msg.is_a?(String)
          = content_tag :div, msg, :class => 'alert alert-info', :id => "flash_#{name}"

app/views/layouts/_topbar.haml
#topbar
  .navbar.navbar-fixed-top
    .navbar-inner
      .container
        %a.btn.btn-navbar{'data-target' => '.nav-collapse', 'data-toggle' => 'collapse'}
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.brand{:href => root_path} Orin
        .container.nav-collapse
          - if user_signed_in?
            %ul.nav
              %li.divider-vertical
              %li= link_to t('.new_topic'), mercury_editor_path_helper(new_topic_path)
            %ul.nav.pull-right
              %li.avatar= image_tag current_user.gravatar_url(:size => 30)
              %li= link_to current_user.email
              %li= link_to 'My info', edit_user_registration_path
              %li= link_to 'Sign out', destroy_user_session_path, :method => :delete
          - else
            %ul.nav.pull-right
              %li= link_to 'Sign up', new_user_registration_path
              %li= link_to 'Sign in', new_user_session_path

app/views/layouts/application.haml
!!! 5
%html
  %head
    %meta{charset: 'utf-8'}
    %title Orin
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    - if content_for? :head
      = yield :head
    = csrf_meta_tags

  %body
    = render :partial => 'layouts/flash_content'
    = render :partial => 'layouts/topbar'
    = yield
    = render :partial => 'layouts/footer'

app/views/layouts/mercury.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, maximum-scale=1.0, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <title>Mercury Editor</title>
    <%= stylesheet_link_tag    'mercury' %>
    <%= javascript_include_tag 'jquery-1.7', 'mercury', 'mercury_customize' %>
  </head>
  <body>
    <script type="text/javascript">
      // Set to the url that you want to save any given page to, leave null for default handling.
      var saveUrl = null;

      // Instantiate the PageEditor
      new Mercury.PageEditor(saveUrl, {
        saveDataType: 'json', //'xml', 'json', 'jsonp', 'script', 'text', 'html' (defaults to json)
        saveStyle:  'form', // 'form', or 'json' (default json)
        saveMethod: 'POST', // 'PUT', or 'POST', (create, vs. update -- default PUT)
        visible:    true  // boolean - if the interface should start visible or not
      });
    </script>
  </body>
</html>

app/views/topics/_reply_bar.haml
= form_for replies_path do |f|
  = f.text_field :content, :class => 'reply-input-bar'
  = f.submit "Reply", :class => 'reply-submit'

app/views/topics/_topic.haml
.row
  .span1.offset1
    %li.topic-avatar
      = image_tag topic.user.gravatar_url(:size => 50)
  .span6
    %li.topic
      .topic-info
        = raw topic.user.username
      .topic-admin-controllers
        - if topic.user == current_user
          = link_to raw("<i class=\"icon-trash icon-white\"></i>"), topic, :data => {:confirm => 'Are you sure?'}, :method => :delete
          = link_to raw("<i class=\"icon-edit icon-white\"></i>"), mercury_editor_path_helper(edit_topic_path(topic))
      .topic-content
        = raw topic.content
      .topic-reply-controllers
        = link_to raw("<i class=\"icon-comment icon-white\"></i>"), all_reply_path(topic), :method => :get, :remote => true, 
          'data-type' => 'json', :class => 'topic-replies'
      .topic-replies{'class' => "topic-replies-#{topic.id}", 'data-expended' => 'false'}
        .replies-content{'class' => "replies-content-#{topic.id}"}
        .reply-input{:class => "reply-input-#{topic.id}"}

app/views/topics/_topic_content.haml
.control-group
  .control-label
    %label
      = t('.Content')
  .controls
    #topic_content{'data-mercury' => 'full', :style => 'height: 260px'}
      = raw topic.content

app/views/topics/edit.haml
.container
  .row
    .span10.offset1
      = render :partial => 'form', :object => @topic, :as => 'topic'
#mercury-save-helper{'data-save-url' => mercury_update_topic_path(@topic)}

app/views/topics/index.haml
.container
  .row.dashboard
    .span10.offset
      %ol.no-style
        = render :partial => 'topic', :collection => @topics

app/views/topics/new.haml
.container
  .row
    .span10.offset1
      = render :partial => 'topic_content', :object => @topic, :as => 'topic'
#mercury-save-helper{'data-save-url' => '/topics'}

app/views/topics/show.haml
= debug current_user.topics

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>